### ISSUE TITLE
你这怎么实现检测单独目标

### ISSUE THREAD

**Issue by GrayTempest-400** [DuGuYifei/Yolov5_FPS_AICheatPrinciple#1]
我看你源码都是抄detect.py，也没识别单独的person啊

**Comment by GrayTempest-400** [comment]
是训练的专门检测人的数据集吗

**Comment by GrayTempest-400** [comment]
还是要填aims

**Comment by GrayTempest-400** [comment]
而且单独person不会攻击到队友？

**Comment by DuGuYifei** [comment]
1. 这是个基础demo，真能用于游戏的被我private了。
2. 这个基础的版本就相当于用yolov5源码来做的，我咋可能自创yolo呢 :)，主要是把里面冗余的代码或库去掉。然后跟detect.py不同的地方在于把里面逻辑从import的库里抽出来一些，直接放进了主函数，比如可能它用的import库里的函数只需要抽出函数逻辑里的一两行就行了，根本用不着那个完整的函数。
3. 你要是想单独person，其实完全可以从数学角度和游戏角度入手，不用从AI角度，hmmm，我只能说到这了，hhhh，我在做完这个项目后，有人给我发了一些收费的AI挂，我特地看了看，都是这么干的。（至于不攻击到队友，只能说尽量单排，多人的话，他们会把它称之为辅助，就是主播用的那种，仅识别准星的小区域就行了，找人靠自己）
4. 但是我确实有个问题，哪怕是在我的private里的项目，就是它太准了，导致跟后座一起出现时，屏幕会有点抖，我本就晕3d，在训练场就把自己晕完了。直到有人告诉我说一般想将AI从辅助转成挂，是结合AI识别和无后座一起，我才理解。
