### ISSUE TITLE
鼠标输入问题怎么解决的？

### ISSUE THREAD

**Issue by LeeeSe** [DuGuYifei/Yolov5_FPS_AICheatPrinciple#2]
win32  ghub 都试了不行，现在门槛这么高了吗

**Comment by DuGuYifei** [comment]
试试C++，是可以的

**Comment by LeeeSe** [comment]
C++ 调用 win32api？跟python有区别吗？我大概调查了一下现在都得外部硬件辅助模拟鼠标

**Comment by qq846511277** [comment]
V2版 里面缺了个模型啊

**Comment by DuGuYifei** [comment]
> V2版 里面缺了个模型啊

在readme里面可以看到模型下载地址的 ~~

**Comment by glpc** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'valorant-bot.pt' 一个关键的模型文件不给出来，钩味口。readme里也没找到啊！玩呢！躲猫猫啊！浪费老子时间。

> > V2版 里面缺了个模型啊
> 
> 在readme里面可以看到模型下载地址的 ~~

**Comment by qq846511277** [comment]
傲慢之最！
&nbsp;


超级酷的人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月16日(星期四) 下午2:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DuGuYifei/Yolov5_FPS_AICheatPrinciple] 鼠标输入问题怎么解决的？ (Issue #2)





 
FileNotFoundError: [Errno 2] No such file or directory: 'valorant-bot.pt' 一个关键的模型文件不给出来，钩味口。readme里也没找到啊！玩呢！躲猫猫啊！浪费老子时间。
   
V2版 里面缺了个模型啊
  
在readme里面可以看到模型下载地址的 ~~

**Comment by DuGuYifei** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'valorant-bot.pt' 一个关键的模型文件不给出来，钩味口。readme里也没找到啊！玩呢！躲猫猫啊！浪费老子时间。
> 
> > > V2版 里面缺了个模型啊
> > 
> > 
> > 在readme里面可以看到模型下载地址的 ~~

这仓库这就是研究一下原理的，你是来找挂的。然后找不着不代表没有，找不着可以问，而不是无能狂怒，像个RZ。

**Comment by glpc** [comment]
操蛋，同样是九年义务教育，感觉你好优秀，好利害。咱像是个RZ，哥能上Github，能上GPU，能上PyTorch，能上Yolo，也你想的那么差。就是想练练手，想玩玩，看看你这个高手的优秀代码。不可以吗？一圈下来感觉是浪费了时间。	
1.使用鼠标中键来开启和关闭。
2.鼠标，左击 或 右击，屏幕区块截图，图片降维。【如果截图中没有目标会怎么样？】
3.Yolo处理，计算结果，获取鼠标位置，计算移动信息，移动鼠标。【反作弊机制鼠标移动速度，软件/硬件/模拟鼠键】

**Comment by glpc** [comment]
亮瞎狗不找挂，忘了告诉你，LZ不玩游戏，不喜欢时间浪费在没意义的事情上。把时间放在做有意义的事情上，什么是有意义？有意义就是好好活着。

**Comment by DuGuYifei** [comment]
> > V2版 里面缺了个模型啊
> 
> 在readme里面可以看到模型下载地址的 ~~

原库换名字了，可用roboflow + yolov8 integration网站快速训练。
